"""empty message

Revision ID: 504afdfa9ade
Revises: a5cffa318ac2
Create Date: 2023-12-13 18:05:54.568753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504afdfa9ade'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('bandera', sa.String(length=250), nullable=False),
    sa.Column('himno', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciudad')
    # ### end Alembic commands ###
