"""empty message

Revision ID: c4b3e057b867
Revises: 504afdfa9ade
Create Date: 2023-12-15 18:29:55.898836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b3e057b867'
down_revision = '504afdfa9ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campeonato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('premio', sa.String(length=250), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campeonato')
    # ### end Alembic commands ###
